### PR TITLE
Rewrite code generation using SourceMaps

### LINKED ISSUE #295: Vue 3 source map line numbers are off
https://github.com/vuejs/vue-jest/blob/51fe4ef99d3b29ebdace49a97f380227b6cc6923/lib/generate-source-map.js#L39

This seems to be off by descriptor.script.loc.start.line - 1. Line numbers seem to line up after I added that value.

Pulled this from the 5.0.0-alpha.5 circleCI run
```
--------------------------|----------|----------|----------|----------|-------------------|
File                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------------|----------|----------|----------|----------|-------------------|
All files                 |    83.33 |      100 |       75 |    83.33 |                   |
 basic                    |      100 |      100 |      100 |      100 |                   |
  babel.config.js         |      100 |      100 |      100 |      100 |                   |
 basic/components         |    82.35 |      100 |       75 |    82.35 |                   |
  Basic.vue               |    66.67 |      100 |    66.67 |    66.67 |                21 |
  BasicSrc.vue            |    66.67 |      100 |    66.67 |    66.67 |                20 |
  Coffee.vue              |        0 |        0 |        0 |        0 |                   |
  CoffeeScript.vue        |        0 |        0 |        0 |        0 |                   |
  FunctionalSFCParent.vue |      100 |      100 |      100 |      100 |                   |
  Jsx.vue                 |        0 |      100 |        0 |        0 |                 4 |
  NamedExport.vue         |      100 |      100 |      100 |      100 |                   |
  RenderFunction.vue      |      100 |      100 |      100 |      100 |                   |
  TypeScript.vue          |      100 |      100 |      100 |      100 |                   |
  TypeScriptChild.vue     |      100 |      100 |      100 |      100 |                   |
--------------------------|----------|----------|----------|----------|-------------------|
Test Suites: 1 passed, 1 total
Tests:       3 skipped, 13 passed, 16 total
Snapshots:   2 passed, 2 total
Time:        4.438s
Ran all test suites matching /test.js/i.
Done in 5.42s.
```
Note that in Basic.vue Line 21 is not accurate. That should say 43.

https://github.com/vuejs/vue-jest/blob/51fe4ef99d3b29ebdace49a97f380227b6cc6923/e2e/__projects__/basic/components/Basic.vue#L43

In that case. `descriptor.script.loc.start.line` is 23
the proper line number is 43. Basically 21 + 23 - 1

### PR DESCRIPTION
**Pull request by jolting**
This change remaps the source line numbers back to the original Vue files.
It fixes #295

### CODE REVIEW

**Comment by jolting** [comment]
```
--------------------------|----------|----------|----------|----------|-------------------|
File                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------------|----------|----------|----------|----------|-------------------|
All files                 |    84.62 |      100 |    64.29 |    86.49 |                   |
 basic                    |      100 |      100 |      100 |      100 |                   |
  babel.config.js         |      100 |      100 |      100 |      100 |                   |
 basic/components         |    84.21 |      100 |    64.29 |    86.11 |                   |
  Basic.vue               |       75 |      100 |    66.67 |       75 |                43 |
  BasicSrc.js             |       75 |      100 |    66.67 |       75 |                20 |
  Coffee.vue              |      100 |      100 |      100 |      100 |                   |
  CoffeeScript.vue        |      100 |      100 |      100 |      100 |                   |
  FunctionalSFCParent.vue |      100 |      100 |      100 |      100 |                   |
  Jsx.vue                 |       50 |      100 |        0 |       50 |                 4 |
  NamedExport.vue         |      100 |      100 |      100 |      100 |                   |
  Pug.vue                 |      100 |      100 |      100 |      100 |                   |
  PugRelativeExtends.vue  |      100 |      100 |      100 |      100 |                   |
  RenderFunction.vue      |      100 |      100 |      100 |      100 |                   |
  ScriptSetup.vue         |    66.67 |      100 |        0 |       75 |             14,15 |
  TypeScript.vue          |      100 |      100 |      100 |      100 |                   |
  TypeScriptChild.vue     |      100 |      100 |      100 |      100 |                   |
--------------------------|----------|----------|----------|----------|-------------------|
```
These source maps are accurate now.

https://github.com/vuejs/vue-jest/blob/75aee3173baf46360441da7346a9b0a5d8a6e83f/e2e/__projects__/basic/components/Basic.vue#L43

https://github.com/vuejs/vue-jest/blob/75aee3173baf46360441da7346a9b0a5d8a6e83f/e2e/__projects__/basic/components/BasicSrc.js#L20

https://github.com/vuejs/vue-jest/blob/75aee3173baf46360441da7346a9b0a5d8a6e83f/e2e/__projects__/basic/components/Jsx.vue#L4

https://github.com/vuejs/vue-jest/blob/75aee3173baf46360441da7346a9b0a5d8a6e83f/e2e/__projects__/basic/components/ScriptSetup.vue#L14

**Comment by JPrevost** [comment]
@jolting just wanted to let you know this seems to resolve a problem I'm having with the line numbers being wrong for coverage. I hope this can get through code review and thanks for digging in on this as I was chasing this through and trying to figure out _where_ the problem was even coming from in the stack of dependencies around testing in vue3 with jest.

**Comment by jolting** [comment]
@JPrevost it wasn't hard once I found this mapLines trick.
https://github.com/vuejs/vue-next/blob/dcb29496ba62a1d5921cc0d26490a246b28966af/packages/compiler-sfc/src/compileTemplate.ts#L188
I wish they exported that function though. It's slick.

**Comment by lmiller1990** [comment]
Wow, great work! I will review this tonight and hopefully push this out in a day or two, assuming no problem. Anything you think I should look at specifically?

PS if we need something exported from Vue 3 core we could look at making that happen too, but it looks like you solved everything here as is.

**Review by lmiller1990 — APPROVED** [review]
Seems fine, nice job 🎉 
I can release this weekend.

**Comment by jolting** [comment]
@lmiller1990 if compiler-sfc can export the mapLines then that would at the very least remove the code duplication and vue-jest can just `import { mapLines } from '@vue/compiler-sfc'` That would eliminate the extra file I added.

**Comment by lmiller1990** [comment]
Yeah I figured. We can release this as-is for now so people get good coverage.

You could file an issue in Vue core regarding exporting that `mapLines` function. I don't see why it couldn't be exposed for this reason.

**Pull request merged**
