### PR TITLE
deps: `source-map` updated to 0.6.1

### PR DESCRIPTION
**Pull request by Asim-Tahir**
fix: #328 i hope 🙏

### CODE REVIEW

**Comment by Asim-Tahir** [comment]
@lmiller1990 👀

**Comment by lmiller1990** [comment]
Can you reproduce the original problem here? Any way to verify this actually solves the problem (and doesn't introduce a regression?)

**Comment by Asim-Tahir** [comment]
https://github.com/vuejs/vue-jest/releases/tag/v5.0.0-alpha.9 fixed this issue. No need for this PR. Im close this.

**Comment by lmiller1990** [comment]
Good to hear!

**Pull request closed without merging**
