### PR TITLE
Support Jest 25

### PR DESCRIPTION
**Pull request by sibiraj-s**
Jest 25 is released https://jestjs.io/blog/2020/01/21/jest-25.

### CODE REVIEW

**Comment by sibiraj-sr** [comment]
@JessicaSachs @lmiller1990 can we merge this and release a stable stable version of v4. its been more than a year since the last beta was release. plus vue3 is now in beta state.

see #206

**Comment by JessicaSachs** [comment]
We're very aware that Vue 3 is in beta. We're working non-stop on supporting Vue Test Utils for Vue 3.

RE Stable: The last decision to make is regarding native typescript support and choosing ts-jest or babel-jest for built-in typescript support. We're busy with Vue 3 support so this hasn't gotten attention.

**Comment by utlime** [comment]
Hi @JessicaSachs , could you please merge this PR, as current version has vulnerability: 
https://app.snyk.io/test/npm/ts-jest/24

**Comment by lmiller1990** [comment]
I approved. @JessicaSachs we good to merge this and do a minor for vue-jest v3?

**Comment by utlime** [comment]
Hey @lmiller1990 , it will be good to release for v4.0.0-beta.3 as we started to use beta version

**Comment by lmiller1990** [comment]
Oh yes, that probably makes more sense @utlime.

I will wait for 1-2 days to see @JessicaSachs opinion. Then we can do it.

I think we should make this 4.0.0 release candidate 1 - I don't see any real benefit in dragging this out. I've been using v4 beta for a while and it seems fine ✅

**Comment by andrew-ignatiev** [comment]
@lmiller1990 @JessicaSachs . First of all thank you for your great work! Do you have plan to merge it? If so, when community will be able to get it and forget about annoying vulnerability finally? :)

**Comment by lmiller1990** [comment]
Right now

**Comment by lmiller1990** [comment]
I will release v4.0.0-beta.3 in an hour or so, waiting on CI and testing a bit.

We need to get into gear and sort this mess out, we have v3, v4 AND v5 (for Vue 3).

Clearly v3 needs to be deprecated, I have literally no idea what the difference is between v3 and v4 (only just joined this repo a month or so ago).

Does anyone know? Can someone try upgrading from v3 to v4 and see if anything breaks? It worked fine on my small/medium apps.

**Comment by lmiller1990** [comment]
Ok 4.0.0-beta.3 should now be available on NPM.

**Comment by lmiller1990** [comment]
https://github.com/vuejs/vue-jest/releases/tag/v4.0.0-beta.3

**Pull request merged**
