### PR TITLE
ci: setup GitHub Actions

### PR DESCRIPTION
**Pull request by nogic1008**
*Note: To take advantage of this PR, you need to enable GitHub Actions on this repository.*
[sample jobs](https://github.com/nogic1008/vue-jest/actions/runs/249295082)

- Setup GitHub Actions workflow
  - Node.js 10, 12, 14
  - ~~Jest 24, 25, 26~~
- bump `@babel/core` and `@babel/preset-env` to `7.9.0` to fix error in Node.js 12 or above

### CODE REVIEW

**Comment by lmiller1990** [comment]
Interesting. Is there an advantage to GH actions over Circle CI for example?

**Comment by nogic1008** [comment]
@lmiller1990 
### Advantage:
- Circle CI cannot watch test results without signing up, but GitHub Actions can do.
- Circle CI can also use [matrix jobs](https://circleci.com/blog/circleci-matrix-jobs/), but free plan don't run in parallel. It will take more time.
- Testing can be done even in forked repositories. (need to opt in there)
- Lots of reusable actions (like orb in Circle CI) are available in the community.

### Disadvantage:
- GitHub Actions cannot rerun job partially. only can "Rerun All".
- It is difficult to access the running job with SSH etc.

**Comment by lmiller1990** [comment]
Sounds like we should ues GH actions. I will look into this on the weekend. Thanks!

**Comment by nogic1008** [comment]
@lmiller1990 
Thank you for your interest.
This PR conflicts with #284, so I'll rebase it after 284 has been merged.

**Comment by nogic1008** [comment]
@lmiller1990 
Ready to merge. After merged, we can delete `/.circleci` folder safely. 
[GitHub Actions result](https://github.com/nogic1008/vue-jest/actions/runs/681822090)

**Comment by lmiller1990** [comment]
Forgot this, sorry! I sent you a msg on Twitter regarding this PR, let's chat.

**Comment by lmiller1990** [comment]
Thanks @nogic1008, feel free to make any other improvements you see, I can review your PRs :)

**Pull request merged**
