### PR TITLE
release 4-rc.0 and update jest and ts-jest to 26.x

### PR DESCRIPTION
**Pull request by aantipov**
Release 4.0.0-rc.0 which includes the fix for https://github.com/vuejs/vue-jest/issues/241
Also bump `jest` and `ts-jest` versions to 26.x

### CODE REVIEW

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
It's out, can you test it out? `yarn add vue-jest@4.0.0-rc.0`.

Thanks!

**Comment by DerAlbertCom** [comment]
Any chance to get this to vue-jest 5 alpha for the devs who who like to use Vue 3 and a newer Typescript version?

**Comment by DerAlbertCom** [comment]
Any way, to get ts-jest in a current version in  5 alpha?

**Comment by lmiller1990** [comment]
What exactly do you mean? Just change the version we are using?

**Pull request merged**
