### PR TITLE
Fix source maps for vue2-jest

### PR DESCRIPTION
**Pull request by NikhilVerma**
The code has been borrowed from vue3-jest

For me this fixes: https://github.com/vuejs/vue-jest/issues/474

### CODE REVIEW

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
CI is failing - can you take a look?

**Comment by NikhilVerma** [comment]
@lmiller1990 I've fixed the test issues, it was a path mismatch between my machine and the github CI agent. Can you pls re-run the CI? I don't have the permissions to do so.

**Comment by john-maddock** [comment]
@NikhilVerma im using vue2-jest but not using typescript, im also having source map issues. Wondering will this fix it for ?..

**Comment by lmiller1990** [comment]
Looks good, I'll leave this open until I've got bandwidth to release, that should be in the next few days. Ping me if it does not happen.

@john-maddock no idea, you could test it out by just copy pasting the changes into your node_modules/vue-jest directory - no need to compile, it's regular JS.

**Comment by lmiller1990** [comment]
Let's wait for  https://github.com/vuejs/vue-jest/pull/483 to merge, then I'll merge this and release the new version.

**Comment by lmiller1990** [comment]
Let's just ship this.

**Comment by lmiller1990** [comment]
It's out https://github.com/vuejs/vue-jest/releases/tag/v28.1.0

**Pull request merged**
