### PR TITLE
fix: `lang='tsx'` doesn't work for Vue 3 SFC

### LINKED ISSUE #510: Is it possible to add support for lang="tsx" in sfc?
Is it possible to add support for lang="tsx" in sfc?
Currently, when testing sfc with lang="tsx", an error will be reported
image

### PR DESCRIPTION
**Pull request by sevilyilmaz**
Applies the same fix that is added for Vue 2 with this PR: #395

Resolves #510

### CODE REVIEW

**Comment by sevilyilmaz** [comment]
@lmiller1990 @cexbrayat could you check this PR? (Pinging you as I'm not sure if you already got a notification or not)

**Comment by cexbrayat** [comment]
LGTM (but I no longer actively maintain this as we switched to vitest to run our tests)

**Comment by sevilyilmaz** [comment]
I understand the reasoning.

It would be great to have PRs for bug fixes reviewed and released. Because it’s not straightforward to switch to vitest especially on big monorepos

**Comment by lmiller1990** [comment]
I too do not really use / maintain this, but I will review and release your fix, give me until the end of the week (5th or 6th of Aug).

We really need someone who is actively invested in this repo, for now I'm happy to do the minimum of review / release patches, but I only check when someone pings me.

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
@sevilyilmaz done: https://github.com/vuejs/vue-jest/releases/tag/v29.2.5

**Comment by sevilyilmaz** [comment]
@lmiller1990 thank you!

**Pull request merged**
