### PR TITLE
Issue #417: Should not return empty string so that it is compatible w…

### PR DESCRIPTION
**Pull request by lptai**
Fix issue mentioned here https://github.com/vuejs/vue-jest/issues/417

### CODE REVIEW

**Comment by lmiller1990** [comment]
Can you try merging in the latest master? Sorry for the slow response.

**Comment by Magiczne** [comment]
@lptai will you update this PR? If not i will go and create a fresh one based on the current master, cause that bug is holding me in my projects

**Comment by lptai** [comment]
Doing it now @Magiczne

**Comment by lptai** [comment]
> Can you try merging in the latest master? Sorry for the slow response.

updated to latest master @lmiller1990

**Comment by lmiller1990** [comment]
Will review soon, thanks.

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
It's released. https://github.com/vuejs/vue-jest/releases/tag/v28.0.0

You might need to update to Jest 28 to get this; I don't think it got in the last release for v27. If this is big problem, let me know, but updating to the latest Jest is always a good idea.

**Pull request merged**
