### PR TITLE
Improve .babelrc lookup

### PR DESCRIPTION
**Pull request by TheCycoONE**
Now searches with a depth of infinity from the file path, as described
in #66.

For my personal use, just switching the depth from 0 to the default (INFINITY) was enough; but as per the ticket I try to use the filePath now as well.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
The issue is that the test is being run in `vue-jest/temp-dir` where the .babelrc is being renamed; but the search finds the babelrc in vue-jest now.

**Comment by eddyerburgh** [comment]
Thanks for the PR. 

What's your use case?

**Comment by TheCycoONE** [comment]
The ability to run jest from anywhere in the npm project, particularly the location of the spec file.

In particular this allows IntelliJ's Jest plugin to run without configuration in the IDE. It is also consistent with babel-jest.

**Comment by eddyerburgh** [comment]
We should keep the same functionality as babel-jest, but I don't think babel-jest searches in parent directories for the babel config file. 

I'll have to take a deeper look at the source code. From what I could tell the babel options are found when the transformer is initially created, which I think is in the project root. We could implement something similar.

**Comment by TheCycoONE** [comment]
My understanding is that this loop removes the last part of the path until it hits the root or escapes due to cache or finding the config. I have made an assumption about the filename being passed in, I could test that later if you like. https://github.com/facebook/jest/blob/4a46993b5116838a55666ac8c0522a71457eb7c5/packages/babel-jest/src/index.js#L37

**Comment by eddyerburgh** [comment]
You're right, it does.

Ok, how about we rename the root babelrc as part of the test script, so it doesn't find it when the tests are running, then rename when the process exits?

**Comment by TheCycoONE** [comment]
My feeling is that it is better to mock our findBabelConfig dependency so we aren't escaping the test sandbox, and the unit tests are more contained. I'm quite open to your feedback though

**Comment by TheCycoONE** [comment]
I made the test changes as you suggested.

**Comment by eddyerburgh** [comment]
Hey, sorry that I've been silent on this. It slipped my radar.

I agree that we should add this feature, but we need a test for the filepath functionality specifically. Are you able to add a test to check that the babelrc searching uses the current directory?

**Comment by TheCycoONE** [comment]
Sure, no problem. Likely tomorrow.

**Comment by TheCycoONE** [comment]
@eddyerburgh Are those the tests you wanted?

**Comment by eddyerburgh** [comment]
Thanks for adding the tests. I was thinking they should be tests that call through the whole `process` function, like [these tests](https://github.com/vuejs/vue-jest/blob/master/test/Babel.spec.js#L37). The reason is that we will be refactoring the project soon and the load-babel-config function might be removed/ refactored. But they are fine as is. Thanks a lot for your patience and for creating this PR :)

**Pull request merged**
