### PR TITLE
Fix: support for class component mixins

### PR DESCRIPTION
**Pull request by Evertvdw**
Fix for using class component with mixins and also for importing
Vue from vue-property-decorator instead of vue-class-component.

See for more details: https://github.com/vuejs/vue-test-utils-next/issues/544

### CODE REVIEW

**Comment by Evertvdw** [comment]
@lmiller1990 Any chance you can take a look at this?

**Review by lmiller1990 — APPROVED** [review]
Nice job figuring this out! This is probably the most confusing part of the code base.

**Comment by Evertvdw** [comment]
Thanks! Credits to you though, without your video on debugging this earlier I wouldn't have gotten there ;)

**Comment by lmiller1990** [comment]
I should make some more videos explaining how this code base (and Test Utils) work - at the moment neither of them is very approachable (especially this code base - this is one of the most complex Jest transformers out there).

I'll wait until the end of the week and do a release... hopefully we can get [this issue fixed and merged, too](https://github.com/vuejs/vue-jest/issues/332).

**Pull request merged**
