### PR TITLE
feat: jest v27 support for vue2-jest

### PR DESCRIPTION
**Pull request by cexbrayat**
Followup, and quasi identical PR to #343 

@lmiller1990 if that looks good, it would be nice to have an alpha release. I think I need it to update the CLI to jest 27 (as it looks like I need to bump Vue 3 and Vue 2 projects at the same time)

### CODE REVIEW

**Comment by lmiller1990** [comment]
I will do this week, sorry about the delay.

**Comment by lmiller1990** [comment]
Alpha release will be in 24-48h! Thanks for the patience.

**Comment by lmiller1990** [comment]
@cexbrayat just to confirm and make sure we are on the same page, we want this released under `vue-jest@27.0.0-alpha.0`?

`vue2-jest` is not available as you pointed out (I think it was you). I need to email `npm` to get access: https://www.npmjs.com/package/vue2-jest

**Comment by cexbrayat** [comment]
@lmiller1990 No, I don't think we should release it as vue-jest v27. It would be too confusing in my opinion to have vue-jest v4 for vue 2, v5 for vue 3 and v27 for vue 2 again. If we publish vue-jest v27, it should be the same as vue3-jest v27.

Ideally, it would be nice to have `vue2-jest` back from NPM, or maybe we could publish this under `@vue` (`@vue/vue2-jest` and `@vue/vue3-jest`?).

**Comment by afontcu** [comment]
Publishing under `@vue` looks like a valid solution? It makes total sense as it in an official package

**Comment by lmiller1990** [comment]
Ok, I will publish it under `vue` for now (not sure if need any special permissions, I'll give it a shot).

We will need to reach out to npm regarding `vue2-jest`. I will look into this, although it might need to come from a `@vuejs.org` email. Let's see how it goes. I'll report back.

**Pull request merged**
