### PR TITLE
Remove ts-jest dependency

### PR DESCRIPTION
**Pull request by lmiller1990**

### CODE REVIEW

**Comment by nogic1008** [comment]
@lmiller1990 
Could you add yarn lock files into `.gitignore` ?
like this
```gitignore
/e2e/**/yarn.lock
```

**Comment by lmiller1990** [comment]
Hm, can we just move to yarn from npm? I find it way more stable, faster, and better in every way. Any reason to stay with npm?

**Comment by lmiller1990** [comment]
@sodatea can you double check this is the change you asked for regarding the ts-jest dependency? Then I can do a release.

**Comment by nogic1008** [comment]
@lmiller1990 
> Hm, can we just move to yarn from npm? I find it way more stable, faster, and better in every way. Any reason to stay with npm?

I have no intention of returning from `yarn` to `npm`.
`yarn.lock` files in `e2e` folder are regenerated for each test, so it should be gitignored.

**Comment by lmiller1990** [comment]
Right, yes, ok.

**Review by sodatea — APPROVED** [review]
This looks good to me 👍

**Comment by sodatea** [comment]
@lmiller1990 any chance this gets merged? The `ts-jest` dependency is causing really annoying peer dependency warnings in non-ts projects.

**Comment by lmiller1990** [comment]
Oops @sodatea I forgot this. I rebased and resolved the conflicts. This will be released as 4.0.1 within 48h.

**Comment by lmiller1990** [comment]
@sodatea it's out: https://github.com/vuejs/vue-jest/releases/tag/v4.0.1

Let me know if you have any other problems. Thanks!

**Pull request merged**
